### PR TITLE
Winds sample data 

### PR DESCRIPTION
**Pull request by pp-mo**
To support https://github.com/bjlittle/geovista/pull/676

### CODE REVIEW

**Comment by pp-mo** [comment]
**WIP do not merge**

First, I'll just check that this data will work via pooch + gv.pantry
...

**Comment by pp-mo** [comment]
Ok, I checked it !
Should now work.

**Comment by pp-mo** [comment]
@bjlittle ping!
I think this is the right data.
Please let me know if we need more than just adding this 1 file ?

**Comment by bjlittle** [comment]
@pp-mo Do you need both timesteps in the data?

**Review by bjlittle — APPROVED** [review]
@pp-mo Awesome, looks good to me :+1:

**Comment by pp-mo** [comment]
> @pp-mo Do you need both timesteps in the data?
I don't really, nor the 4-5 vertical levels.
But the file is already quite small + the dims at least match the structure of the original.
Plus it may prove handy to have some more dims in future.

**Pull request merged**
